# netlify.toml
[build]
  # Configuraci贸n del directorio de publicaci贸n
  publish = "dist" # Cambia "dist" si tu carpeta de compilaci贸n tiene otro nombre
  command = "pnpm build" # Comando para construir el proyecto

# Configuraci贸n de headers
[[headers]]
for = "/*" # Aplica a todas las rutas
[headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
  Access-Control-Allow-Headers = "Content-Type, Authorization"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
