[build]
  publish = "dist" # Cambia "dist" si tu carpeta de build tiene otro nombre
  command = "pnpm build" # Comando para construir el proyecto

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
    default-src 'self';
    connect-src 'self' https://core-backend-gesiar-d4d2aqb2gac6ggc7.canadacentral-01.azurewebsites.net;
    script-src 'self' 'unsafe-inline' 'unsafe-eval';
    style-src 'self' 'unsafe-inline';
    img-src 'self' data: https:;
    font-src 'self' https:;
    frame-ancestors 'none';
    """
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://gesiar.netlify.app"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, Content-Type, Accept, Authorization"
    Cache-Control = "no-cache"

[[redirects]]
  from = "/api/*"
  to = "https://core-backend-gesiar-d4d2aqb2gac6ggc7.canadacentral-01.azurewebsites.net/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
