[build]
  # Configuración del directorio de publicación
  publish = "dist" # Cambia "dist" si tu carpeta de compilación tiene otro nombre
  command = "pnpm build" # Comando para construir el proyecto

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://gesiar.netlify.app"
    Access-Control-Allow-Credentials = "true"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://core-backend-gesiar-d4d2aqb2gac6ggc7.canadacentral-01.azurewebsites.net"

[[redirects]]
  from = "/api/*"
  to = "https://core-backend-gesiar-d4d2aqb2gac6ggc7.canadacentral-01.azurewebsites.net/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
